### ISSUE TITLE
Where are we at with this vocab section?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/agent#56]
@Connoropolous suggests [in this hylo proposal](https://www.hylo.com/p/12324),

> Collaborative development of a vocabulary that results in a standardized schema for crucial data types such as 'people' 'groups' and many more. 

I get the impression that the VF crew is fairly satisfied with the the people and groups vocab -  [vf:agent](https://github.com/valueflows/agent), and is moving on to other topics. 

Is that true? I'm a little hesitant because we have not made the full round trip to Holodex yet, and @elf-pavlik is out of pocket for awhile.

I'll ask for more use cases from Hylo...

**Comment by fosterlynn** [comment]
@bhaugen @Connoropolous I feel satisfied with the basic model, and definitely have moved on.... for now.....

There are a few missing links that I can think of:
-- What existing vocab elements do we want to explicitly use? (foaf:Agent? etc.)
-- What types of Agents do we want to explicitly define as part of VF, beyond the use of other vocab items for this?
-- What types of Agent Relationships do we want to explicitly define as part of VF?
-- It needs an upgrade on documentation.

And yes it would be good to complete the Holodex round trip, although @ahdinosaur 's browser goes a long way towards this.  But we could do that with the proposed use case with Next Edge too. https://www.hylo.com/p/12324

I also feel like we need @elf-pavlik around to complete the missing links, but that shouldn't stop us from moving forward with groups that are interested.  Everyone needs to understand there will be adjustments along the way and that we will be collaborating on each others' development, it won't be a scene where we come in with a polished vocab and others use it. :)

Another area we will need: the whole credentials side: something like UserAccount perhaps, related to Person?  Can work on that with the OAuth efforts?

What do the rest think?

**Comment by ahdinosaur** [comment]
second @fosterlynn's comment as an immediate TODO checklist to finish off this development cycle.

then for another cycle of development, i'm interested in splitting out profiles and credentials from the agent objects.

**Comment by fosterlynn** [comment]
> then for another cycle of development, i'm interested in splitting out profiles and credentials from the agent objects.

@ahdinosaur :+1:  I consider them already split out, just we haven't done them yet. It's possible we will want to do credentials for @Connoropolous .... there is some work in w3c we might be able to make use of, and/or we can do them as part of Connor's effort.

**Comment by fosterlynn** [comment]
I think for purposes of starting to use this for @Connoropolous first use case, I would:
- Just use vf: for Agent, Person, Group for now.  I'm not comfortable with that long term, but I don't feel like I can make a call on using existing vocab (like foaf) without others as part of the decision.  And it doesn't affect the model itself.
- Leave the types of Agents at Group and Person for now, since that is probably all Connor needs.
- Types of relationships:  I would like to add affiliatedWith and hasAffiliate as sub-properties of the vf:relationship rdf:Property.  I think this will cover what Connor needs, and is the "member" relationship but more loosely, therefore more generically stated.  It covers autonomous persons and groups affiliated with a group.  People can subclass off of that as needed - like "member", "harvester" or other roles, etc.  (I think we want to add a couple more generic ones, but probably don't need them now.  These might be a subOf type thing, where the agent is not autonomous; and something for the peer type relationships within a network, like "mentor", "friend".)  

So really, the only addition is the new subProperty of relationship, the last one above.  @ahdinosaur @bhaugen any thoughts?

I'll explore with Connor if there are other attributes or properties he needs.... or Connor, feel free to answer here.....

**Comment by bhaugen** [comment]
@fosterlynn I'm good with all of that.

**Comment by ahdinosaur** [comment]
> Just use vf: for Agent, Person, Group for now.

:+1:. i'm also keen to link the `vf` classes to all equivalent external classes that we're aware of via [`owl:equivalentClass`](http://www.w3.org/TR/owl-ref/#equivalentClass-def).

> Leave the types of Agents at Group and Person for now, since that is probably all Connor needs.

:+1: 

> Types of relationships: I would like to add affiliatedWith and hasAffiliate as sub-properties of the vf:relationship rdf:Property. I think this will cover what Connor needs, and is the "member" relationship but more loosely, therefore more generically stated.

i know we've bikeshedded on this for a while now, but i don't feel `affiliatedWith` and `hasAffiliate` are more generic, they are the specific opinions of how Sensorica thinks of membership, even if it is more loose. i'd prefer we go either either `memberOf` and `hasMember` (which is closest to what everyone expects) or  `groups` and `isGroupedBy` (which seems the most generic to me).

**Comment by bhaugen** [comment]
@ahdinosaur @fosterlynn - I don't care about the name of the relationship. Whatever @Connoropolous thinks would communicate best to the people who will be relating (NextEdge, I guess).

**Comment by fosterlynn** [comment]
> i'd prefer we go either either memberOf and hasMember (which is closest to what everyone expects)

OK let's do it! 

I also don't care, in the sense that I don't think we know how to make a better decision right now.  ( @Connoropolous  mentioned "affiliate" for NextEdge, but I don't think that drives this decision.  I picked up on it because it seemed like he chose it as reflective of the kind of networks that tend to develop these days, looser than membership. Of course many groups and even networks are tighter than that too.  @ahdinosaur I take your point that "member" is a pretty normal term.)  In any case, member it is!

**Comment by fosterlynn** [comment]
OK, back at it again after our break!  :smile:   Really sorry I missed the discussion last Sunday!  

Want to wrap up the use of other vocabs question for Agent.  At least for the elements we actually have defined right now.  Enough to feel like it can be used as input to trying to get some implementations of Agent, which might be stirring now.

So, I am changing vf:Agent to foaf:Agent, vf:Person to foaf:Person, and vf:Group to foaf:Group.  I understand y'all decided that was ok, even though the foaf/Solid developments may impact down the road.  (Looking forward to those!)

I would still like to add org:Organization in parallel with Person and Group, so the concept is documented clearly.  @ahdinosaur do you still not like that?  If not, I'll just leave it be.

I think awhile back we ended up with vf:name rather than vf:label, is that true?  (Couldn't find it in the issues.)  I would like to use vf:name, defined as skos:prefLabel.  Everyone good with that?

Would like to change vf:note to skos:note.  Everyone good with that?

Would like to find existing vocab defs for vf:url and vf:image.  @elf-pavlik or @ahdinosaur thoughts there?  If not, I'll do some research.

Is it possible to do a bit more work on the relationship types, which are subproperties of rdf:Property?  We got memberOf, and tentatively thought about other generic definitions which could be subpropertied further, but which would have some definitional behavior associated with them.  If it is too much, we'll let it be.  Or, how about: partOf/hasPart, peerOf/peerOf?  partOf is like subOf/superOf, except definitionally more different than member, which can be like sub. peerOf takes care of things like mentor, friend, etc.  And customerOf/supplierOf?  I think those would cover the behavioral definitions we need in NRP.  Or, just let it be?  I think I would regard these as still in development while we do some implementations to prove them out, anyway.

**Comment by ahdinosaur** [comment]
@fosterlynn do as you please with the RDF linked data vocab. :smile: everything you mention seems good. i think for Holodex we're going to experiment with an alternative approach in parallel, keeping in mind the overall concepts but without the RDF linked data details.

> Is it possible to do a bit more work on the relationship types, which are subproperties of rdf:Property? We got memberOf, and tentatively thought about other generic definitions which could be subpropertied further, but which would have some definitional behavior associated with them.

hmm, that's an interesting idea. i'm not exactly sure what is the difference between partOf and subOf, but like the idea of having sub-types for general definitional behaviors.

**Comment by bhaugen** [comment]
@ahdinosaur 

>  i think for Holodex we're going to experiment with an alternative approach in parallel, keeping in mind the overall concepts but without the RDF linked data details.

Same model, same vocab, just a different representation? Or different vocab, to some extent?

Anyway, I think we should support different serializations of the model, from json to json-LD to the range of other semantic web formats (Turtle, RDF, whatever). Maybe CSVs. I think my priority is to catch up with Lynn and Pavlik and learn the semweb stuff. But I'll also be interested in what you do, as you move ahead again.

**Comment by fosterlynn** [comment]
@ahdinosaur yes looking forward to seeing what comes out of the Holodex direction!  And I like the parallel technical directions too, although I'm not as in touch as @bhaugen with where y'all are going.

**Comment by ahdinosaur** [comment]
> Same model, same vocab, just a different representation? Or different vocab, to some extent?

same model, same vocab, just a different representation using [tcomb](https://github.com/gcanti/tcomb). if we come across any (major) changes to the model / vocab, i'll raise them here.

**Comment by elf-pavlik** [comment]
Looking at README it seems that we have very minimalistic equivalent of FOAF
- Agent
  - Person
  - Group

I think we just need to clarify little more the Relationship and (has)member(of) and done!

> same model, same vocab, just a different representation using tcomb.

It seems JS specific. Can you still wrap it in [JS RDF Interface](https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md) and than serialize with any of https://github.com/rdf-ext/rdf-ext#serializers ?
